services:
  ollama:
    build: .
    container_name: ollama
    environment:
      - OLLAMA_MODEL=gpt-oss:Q4_0
    healthcheck:
      test: ["CMD", "sh", "-c", "ollama list >/dev/null 2>&1"]
      interval: 20s
      timeout: 5s
      retries: 10
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - mesrag-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    #ports:
    #  - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434/api
      - BACKEND_URL=http://backend:8001
    volumes:
      - backend_data:/app/data
    networks:
      - mesrag-network
    depends_on:
      - ollama

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__ENABLE_API_KEY=true
      - QDRANT__SERVICE__API_KEY=moc-tajny-klic-420
    networks:
      - mesrag-network

  backend:
    build:
      context: ./rag-backend      # složka s Dockerfile a import_documents.py
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=moc-tajny-klic-420
      - OLLAMA_URL=http://ollama:11434/api
      - OLLAMA_MODEL=gpt-oss:Q4_0
      - RELEVANCE_THRESHOLD=0.5
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/embed'); print('ok')"]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - backend_data:/app/data
    depends_on:
      qdrant:
        condition: service_started
      ollama:
        condition: service_healthy
    #ports:
    #  - "8001:8001"
    networks:
      - mesrag-network
    
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - mesrag-network

volumes:
  ollama_data:
  qdrant_data:
  backend_data:

networks:
  mesrag-network:
    driver: bridge
