version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./init.sh:/init.sh
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "chmod +x /init.sh && /init.sh"]
    networks:
      - mesrag-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mesrag_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434/api
    networks:
      - mesrag-network
    depends_on:
      - ollama

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__ENABLE_API_KEY=true
      - QDRANT__SERVICE__API_KEY=moc-tajny-klic-420
    networks:
      - mesrag-network

  importer:
    build:
      context: ./rag-backend      # složka s Dockerfile a import_documents.py
      dockerfile: Dockerfile
    container_name: importer
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=moc-tajny-klic-420
      - OLLAMA_URL=http://ollama:11434/api/embeddings
      - OLLAMA_MODEL=deepseek-r1
    volumes:
      - importer_data:/app/data
    depends_on:
      - qdrant
      - ollama
    ports:
      - "8001:8001"
    networks:
      - mesrag-network

volumes:
  ollama_data:
  qdrant_data:
  importer_data:

networks:
  mesrag-network:
    driver: bridge
