services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./init.sh:/init.sh        # Připojení skriptu do kontejneru
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "chmod +x /init.sh && /init.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data: